server:
  port: 18082
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    import: optional:file:./sandbox.local.yml
  application:
    name: campus-card
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data: # ★ Spring Boot 3：redis 挪到 data 下面了
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${spring.data.redis.password}   # 对应容器启动参数 --requirepass 1234
      database: 1                # 用 1 号库，别跟街坊的 0 号库打架
      timeout: 3000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/campus_card?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: 1234

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.campus.card.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
    banner: false

campus:
  jwt:
    secret: campus-card-secret-key-must-be-at-least-32-bytes-long
    ttl-minutes: 720
  pay:
    notify-url: http://127.0.0.1:18082/api/mock/terminal/notify
    notify-secret: campus-card-notify-secret-2026      # 新增：通知签名密钥
    order-expire-minutes: 15
    retry-backoff-seconds: 30,60,120,240,480
  recon:
    bill-dir: ./bill
  alipay:
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
      # 穿透域名。支付宝的通知是它的服务器发起的，回调地址必须是公网能访问到的
    notify-url: https://morale-citrus-photo.ngrok-free.dev/api/pay/alipay/notify
      # 用户付完钱浏览器被跳回这里（本机地址就行，因为跳转是他的浏览器发起的）
    return-url: http://127.0.0.1:18088/api/pay/alipay/return
      # 我们再把他从他的浏览器送到充值单页面
    return-page: http://127.0.0.1:18088/pay.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.campus.card: debug